### PR TITLE
fix: missing configuration.toml in release packages

### PR DESCRIPTION
**Pull request by mkbhanda**
Signed-off-by: Malini Bhandaru <mbhandaru@vmware.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-cli/blob/master/.github/Contributing.md.

## What is the new behavior?
Bundle contains res directory with configuration.toml

## Does this PR introduce a breaking change?

- [ ] Yes
- [X ] No

## New Imports

- [ ] Yes
- [X ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

Do we want to include an install script or modify docs to give install instructions?
Snaps hashes will need to change too and the location where the configuration.toml is copied to.
## Other information

### CODE REVIEW

**Review by difince — CHANGES_REQUESTED** [review]
Semantic Pull Request fails because you missed to add "fix:" prefix in front of the PR description.
Adding res/configuration.toml file in the tar* file is not enough for fixing the problem. 
We still try to read the configuration file directly from Users Home directory and fail with the same error - `open /home/USER/.edgex-cli/configuration.toml: no such file or directory`
https://github.com/edgexfoundry/edgex-cli/blob/1412a6afd117174be1c1baea27dcde385605b5ca/cmd/root.go#L142

**Comment by mkbhanda** [comment]
Thank you @difince for catching the semantic PR issue. I had mentioned in the PR message the issue you raised ...
"Do we want to include an install script or modify docs to give install instructions?
Snaps hashes will need to change too and the location where the configuration.toml is copied to."

**Comment by difince** [comment]
@mkbhanda, @jpwhitemn, @lenny-intel 
My suggestion for the installation process/documentation is to be like that: 
1. Download the appropriate distribution archive for your operating system containing the edgex-cli executable from [GitHub](https://github.com/edgexfoundry/edgex-cli/releases). 

2. Unpack the `edgex-cli` distribution archive into a desired installation directory {installation dir}.

2. Start the application by opening a console, cd into "{installation dir}" and type:
       ./edgex-cli (device list)
      This should initialize configuration.toml file in the "~/.edgex-cli" directory if it does not exists:

  3. [OPTIONAL] Add "{installation dir}" to your PATH environment
     variable so that `edgex-cli` could be run from any directory.

From implementation point of view Step number 2) means:
Prior executing a command (example `edgex-cli device list`), the application need to validate that ~/.edgex-cli/configuration.toml file exists. 
- If the file exists, it load the configuration and continue with the specified command execution. _( current functionality)_
- If the file does not exists, create directory `~/.edgex-cli` with 744 permissions, and copy ./res/configuration.toml file (already part of the distribution archive done by @mkbhanda ) into the newly created  `~/.edgex-cli` directory and then continue with the execution of the specified command. _(instead of having additional installation script)_ 

Note: at the moment all archives contains edgex-cli executable file under different name:  edgex-cli-linux-amd64, edgex-cli-linux-arm64,  edgex-cli-mac, edgex-cli-win.exe. Let's make them consistent

**Comment by lenny-intel** [comment]
> My suggestion for the installation process/documentation is to be like that:

Sound like a good plan to me. I like that it initializes the toml file the first time so I don't have to worry about copying it to the correct place. From a maintenance perspective,  should remove the default toml file from edgex-cli since there will be duplicate in code and don't want to have to keep them in sync.

**Comment by difince** [comment]
@lenny-intel 
There is not need to keep them in sync. If the configuration.toml file in ~/.edgex-cli directory exists this is the only source of information. But yes, we could accept it could be confusing having two configuration file one in the {installation-dir} and one in ~/.edgex-cli directory. 
But ... I want even if the user delete ~/.edgex-cli directory, to be able to recreate it using the configuration file in the {installation directory}.

**Comment by difince** [comment]
Summarize the decision make in Core WG on 01/07/2021:
- Rename [configuration.toml](https://github.com/edgexfoundry/edgex-cli/blob/master/res/configuration.toml) file used as a template to `.template_configuration.toml` 
- binary edgex-cli  should be responsible to check if configuration.toml file in user HOME directory exists 
If it does not exist - edgex-cli should copy the `.template_configuration.toml` file part of the distribution archive to user HOME dir and notify the user. (no need of installation script)

**Comment by mkbhanda** [comment]
@difince -- love your suggestion to copy configuration.toml if it does not exist on first run, echoing @lenny-intel and the renaming the file to "template-configuration.toml" or sample-configuration.toml, which would remove any confusion.
Much thanks!

**Review by jpwhitemn — DISMISSED** [review]
LGTM - subject to @difince suggestions.

**Comment by mkbhanda** [comment]
Thinking of folding in some symbolic links to the arch specific binaries (keeps the binaries clearly arch specific) and the symbolic link for ease of use. 
Only tested the MAC version, the other linux variants look good, zip looks good, hope the windows exe symbolic works as expected.

**Review by difince — APPROVED** [review]
LGTM

**Comment by difince** [comment]
Prior merging the PR I have tested the fix on Linux machine only. 
After the PR was merged I have tested the fix on windows 10 machine and it gave me an error 
```
C:\Users\home\Downloads\edgex-cli-win-0.0.0>edgex-cli.exe device list
This version of C:\Users\home\Downloads\edgex-cli-win-0.0.0\edgex-cli.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

**Comment by difince** [comment]
In addition once we run `make build-all ` and immediately re rerun the same command - it fails because symbolic links already exists: 
```
difince@difince:~/git/malini/edgex-cli$ make build-all 
echo "GOPATH=/home/difince/git/malini/edgex-cli/go"
GOPATH=/home/difince/git/malini/edgex-cli/go
mkdir -p bin
mkdir -p bin/AMD64
mkdir -p bin/ARM64
mkdir -p bin/MAC
mkdir -p bin/WIN
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 GO111MODULE=on go build -o bin/AMD64/edgex-cli-linux-amd64 -ldflags "-X github.com/edgexfoundry/edgex-cli/cmd/version.Version=0.0.0"; cd bin/AMD64; ln -s edgex-cli-linux-amd64  edgex-cli
GOOS=linux GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on go build -o bin/ARM64/edgex-cli-linux-arm64 -ldflags "-X github.com/edgexfoundry/edgex-cli/cmd/version.Version=0.0.0"; cd bin/ARM64; ln -s edgex-cli-linux-arm64 edgex-cli
GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 GO111MODULE=on go build -o bin/MAC/edgex-cli-mac -ldflags "-X github.com/edgexfoundry/edgex-cli/cmd/version.Version=0.0.0"; cd bin/MAC; ln -s edgex-cli-mac edgex-cli
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 GO111MODULE=on go build -o bin/WIN/edgex-cli-win.exe -ldflags "-X github.com/edgexfoundry/edgex-cli/cmd/version.Version=0.0.0"; cd bin/WIN; ln -s  edgex-cli-win.exe edgex-cli.exe
tar -czvf bin/edgex-cli-linux-amd64-0.0.0.tar.gz Attribution.txt LICENSE -C bin/AMD64 edgex-cli-linux-amd64 edgex-cli
Attribution.txt
LICENSE
edgex-cli-linux-amd64
edgex-cli
tar -czvf bin/edgex-cli-linux-arm64-0.0.0.tar.gz Attribution.txt LICENSE -C bin/ARM64 edgex-cli-linux-arm64 edgex-cli
Attribution.txt
LICENSE
edgex-cli-linux-arm64
edgex-cli
tar -czvf bin/edgex-cli-mac-0.0.0.tar.gz Attribution.txt LICENSE -C bin/MAC edgex-cli-mac edgex-cli
Attribution.txt
LICENSE
edgex-cli-mac
edgex-cli
zip -j --symlinks bin/edgex-cli-win-0.0.0.zip bin/WIN/edgex-cli-win.exe bin/WIN/edgex-cli.exe Attribution.txt LICENSE
updating: edgex-cli-win.exe (deflated 50%)
updating: edgex-cli.exe (stored 0%)
updating: Attribution.txt (deflated 78%)
updating: LICENSE (deflated 65%)


difince@difince:~/git/malini/edgex-cli$ make build-all 
echo "GOPATH=/home/difince/git/malini/edgex-cli/go"
GOPATH=/home/difince/git/malini/edgex-cli/go
mkdir -p bin
mkdir -p bin/AMD64
mkdir -p bin/ARM64
mkdir -p bin/MAC
mkdir -p bin/WIN
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 GO111MODULE=on go build -o bin/AMD64/edgex-cli-linux-amd64 -ldflags "-X github.com/edgexfoundry/edgex-cli/cmd/version.Version=0.0.0"; cd bin/AMD64; ln -s edgex-cli-linux-amd64  edgex-cli
ln: failed to create symbolic link 'edgex-cli': File exists
Makefile:34: recipe for target 'build-all' failed
make: *** [build-all] Error 1
```

**Pull request merged**
